# Generated by Django 2.2.3 on 2019-08-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_id', models.BigIntegerField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'banks',
                'managed': False,
            },
        ),
    ]
